### ISSUE TITLE
bluepot interface doesn't work in debian jessie

### ISSUE THREAD

**Issue by sbrun** [andrewmichaelsmith/bluepot#1]
Hi
Trying to start bluepot in debian jessie gives a completely blank interface.
bluepot is currently in kali linux. And a future release (kali-roling) will be based on debian Jessie.
The bug has been reported here with more details:
https://bugs.kali.org/view.php?id=2177
(we have exactly same results with debian jessie and kali-rolling)

Do you have any idea how to fix that?

thanks

**Comment by andrewmichaelsmith** [comment]
If you run out from a terminal do you get any output?

On 29 April 2015 at 14:17, Sophie Brun <notifications@github.com> wrote:

> Hi
> Trying to start bluepot in debian jessie gives a completely blank
> interface.
> bluepot is currently in kali linux. And a future release (kali-roling)
> will be based on debian Jessie.
> The bug has been reported here with more details:
> https://bugs.kali.org/view.php?id=2177
> (we have exactly same results with debian jessie and kali-rolling)
>
> Do you have any idea how to fix that?
>
> thanks
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/andrewmichaelsmith/bluepot/issues/1>.
>



-- 
Andy Smith
http://andrewmichaelsmith.com | @bingleybeep

**Comment by sbrun** [comment]
Hi,
I have the same message with current version in kali (which works well) and in kali-rolling.
```
ALL:Attempting to initialize bluetooth devices
BlueCove log redirected to log4j
log4j:WARN No appenders could be found for logger (com.intel.bluetooth).
log4j:WARN Please initialize the log4j system properly.
BlueCove version 2.1.0 on bluez
BlueCove version 2.1.0 on bluez
ALL:Sensors initialized
ALL:Loaded sensor configuration
ALL:Starting system..
```

**Comment by andrewmichaelsmith** [comment]
Thanks for the log, I was hoping for a nice helpful error but that all looks OK.

Is there a simple way for me to reproduce this myself? I assume you're using the JAR from - https://github.com/andrewmichaelsmith/bluepot/raw/master/bin/bluepot-0.1.tar.gz?

**Comment by sbrun** [comment]
I tested it in virtual machine with debian jessie and a another with kali-rolling. And I tried with package from kali http://http.kali.org/pool/main/b/bluepot/bluepot_0.1-1kali0_all.deb and with the JAR from https://github.com/andrewmichaelsmith/bluepot/raw/master/bin/bluepot-0.1.tar.gz. Same result.

**Comment by rhertzog** [comment]
@andrewmichaelsmith Any idea? You can try it on a Debian Jessie live image if it helps:
http://cdimage.debian.org/cdimage/release/8.0.0-live/amd64/iso-hybrid/debian-live-8.0.0-amd64-gnome-desktop.iso

**Comment by rhertzog** [comment]
I also tried on a recent Debian Unstable system and I have the same symptom. For your information, if there's no fix in the next 15 days, we will remove bluepot from Kali.

I guess the problem is related to the changes in the Bluetooth stack. In the working distsributions, we have BlueZ 4.99 and in the newer non-working distributions we have BlueZ 5.23. The 5.x version is known to have broken the backwards compatibility quite seriously.

**Comment by andrewmichaelsmith** [comment]
Unfortunately I won't be able to get to a computer until mid August so I
won't be able to make your deadline.

The different dependency version does sound like a likely culprit, thanks
for the pointer I can try and take a look at that when I get the time.

**Comment by andrewmichaelsmith** [comment]
Have put this on https://www.bountysource.com/issues/12486899-bluepot-interface-doesn-t-work-in-debian-jessie

Happy to help anyone trying to get this up and running

**Comment by andrewmichaelsmith** [comment]
I've tracked it down to startListeners which is hanging. The logging is busted so you don't see it but it's spinning on the try/except under if(RFCOMM).

**Comment by ChrisFernandez** [comment]
hello, so if you have tracked it down, are you going to fix it? cheers.

**Comment by andrewmichaelsmith** [comment]
@ChrisFernandez time permitting, but I don't actually understand the issue yet, just where it's occurring. Also happy to accept pull requests.

**Comment by ChrisFernandez** [comment]
Basically it will start with a empty blank screen, no UI just the window, for findings other people did is related to all the new bluetooth libraries in modern linux distributions.

**Comment by srburton** [comment]
BlueScreen ?

![Screenshot from 2019-09-06 14-56-54](https://user-images.githubusercontent.com/15394508/64449574-9c838100-d0b6-11e9-97a6-b04fc4e9f6dc.png)

**Comment by srburton** [comment]
> Tela azul ?
> 
> ![Captura de tela de 2019-09-06 14-56-54](https://user-images.githubusercontent.com/15394508/64449574-9c838100-d0b6-11e9-97a6-b04fc4e9f6dc.png)

Ubuntu 18

**Comment by scotty102** [comment]
Have the same on my kali linux any help please this needs to be fixed.

**Comment by andrewmichaelsmith** [comment]
@rhertzog I imagine it's a bit of a different process, but after 5 years the bug is finally fixed :)
